fixtures:
  forge_modules:
    wget: 
      repo: "maestrodev/wget"
      ref: "1.7.1"
      flags: --verbose
    stdlib: 
      repo: "puppetlabs/stdlib"
      ref: "4.9.0"
      flags: --verbose
    concat:
      repo: "puppetlabs/concat"
      ref: "1.2.0"
      flags: --verbose
  symlinks:
    solr5: "#{source_dir}"
