HOSTS:
  centos-6.6-64-nocm:
    roles:
      - agent
    platform: el-6-x86_64
    hypervisor: vagrant
    box: puppetlabs/centos-6.6-64-nocm
  centos-7.0-64-nocm:
    roles:
      - agent
    platform: el-7-x86_64
    hypervisor: vagrant
    box: puppetlabs/centos-7.0-64-puppet

CONFIG:
  type: foss
  nfs_server: none
  consoleport: 443
  masterless: true
  preserve-hosts: onfail
