HOSTS:
  centos-6.6-64-nocm:
    roles:
      - agent
    platform: el-6-x86_64
    hypervisor: vagrant
    box: puppetlabs/centos-6.6-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-nocm
CONFIG:
  type: foss  
  nfs_server: none
  consoleport: 443
  masterless: true
  preserve-hosts: onfail
